//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.2.0
//     from Assets/_Project/Scripts/Input/AxeInput.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

namespace ChopChop
{
    public partial class @AxeInput : IInputActionCollection2, IDisposable
    {
        public InputActionAsset asset { get; }
        public @AxeInput()
        {
            asset = InputActionAsset.FromJson(@"{
    ""name"": ""AxeInput"",
    ""maps"": [
        {
            ""name"": ""Axe"",
            ""id"": ""7f8ee266-27d3-467d-ad39-1a0e4dc3cc7b"",
            ""actions"": [
                {
                    ""name"": ""Jump"",
                    ""type"": ""Button"",
                    ""id"": ""2cc12db2-339a-4372-a9ca-4ca52744d978"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""3eaf16e4-6d16-4165-96f0-c2dee9af4c6f"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
            // Axe
            m_Axe = asset.FindActionMap("Axe", throwIfNotFound: true);
            m_Axe_Jump = m_Axe.FindAction("Jump", throwIfNotFound: true);
        }

        public void Dispose()
        {
            UnityEngine.Object.Destroy(asset);
        }

        public InputBinding? bindingMask
        {
            get => asset.bindingMask;
            set => asset.bindingMask = value;
        }

        public ReadOnlyArray<InputDevice>? devices
        {
            get => asset.devices;
            set => asset.devices = value;
        }

        public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

        public bool Contains(InputAction action)
        {
            return asset.Contains(action);
        }

        public IEnumerator<InputAction> GetEnumerator()
        {
            return asset.GetEnumerator();
        }

        IEnumerator IEnumerable.GetEnumerator()
        {
            return GetEnumerator();
        }

        public void Enable()
        {
            asset.Enable();
        }

        public void Disable()
        {
            asset.Disable();
        }
        public IEnumerable<InputBinding> bindings => asset.bindings;

        public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
        {
            return asset.FindAction(actionNameOrId, throwIfNotFound);
        }
        public int FindBinding(InputBinding bindingMask, out InputAction action)
        {
            return asset.FindBinding(bindingMask, out action);
        }

        // Axe
        private readonly InputActionMap m_Axe;
        private IAxeActions m_AxeActionsCallbackInterface;
        private readonly InputAction m_Axe_Jump;
        public struct AxeActions
        {
            private @AxeInput m_Wrapper;
            public AxeActions(@AxeInput wrapper) { m_Wrapper = wrapper; }
            public InputAction @Jump => m_Wrapper.m_Axe_Jump;
            public InputActionMap Get() { return m_Wrapper.m_Axe; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(AxeActions set) { return set.Get(); }
            public void SetCallbacks(IAxeActions instance)
            {
                if (m_Wrapper.m_AxeActionsCallbackInterface != null)
                {
                    @Jump.started -= m_Wrapper.m_AxeActionsCallbackInterface.OnJump;
                    @Jump.performed -= m_Wrapper.m_AxeActionsCallbackInterface.OnJump;
                    @Jump.canceled -= m_Wrapper.m_AxeActionsCallbackInterface.OnJump;
                }
                m_Wrapper.m_AxeActionsCallbackInterface = instance;
                if (instance != null)
                {
                    @Jump.started += instance.OnJump;
                    @Jump.performed += instance.OnJump;
                    @Jump.canceled += instance.OnJump;
                }
            }
        }
        public AxeActions @Axe => new AxeActions(this);
        public interface IAxeActions
        {
            void OnJump(InputAction.CallbackContext context);
        }
    }
}
